In [1]:
import pandas as pd
import requests
from pathlib import Path
import json
import datetime

import numpy as np

import load_data as ld
import os

import twitter_lib as tl
import wsj_lib as wsj

In [2]:
coin = 'bitcoin'
coin_ticker='BTC-USD'
num_of_periods = 1000 # 1000 days

start="2018-04-01T00:00:00Z"
end ="2022-04-30T00:00:00Z"
#default bin size of 24H, but we will provide ...just..
bin_size='24H'

In [3]:
sentiment_df = tl.get_crypto_sentiment_from_twitter(coin, num_of_periods, start, end, bin_size)

In [4]:
#bear_sentiment

In [5]:
#bull_sentiment

In [6]:
sentiment_df.head()

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited
Date,,,,,,,,,,,,,,,
2018-04-01,15.0,126.0,39.0,164.0,24.0,8.0,35.0,22.0,2.0,6.0,1.0,188.0,87.0,40.0,100.0
2018-04-02,16.0,116.0,33.0,162.0,12.0,2.0,21.0,10.0,1.0,3.0,1.0,263.0,135.0,15.0,97.0
2018-04-03,26.0,155.0,45.0,171.0,29.0,8.0,30.0,15.0,2.0,1.0,2.0,306.0,121.0,26.0,111.0
2018-04-04,15.0,156.0,37.0,175.0,25.0,4.0,33.0,22.0,1.0,1.0,1.0,265.0,117.0,23.0,97.0
2018-04-05,20.0,123.0,44.0,179.0,29.0,7.0,25.0,20.0,4.0,4.0,1.0,252.0,117.0,22.0,98.0

In [7]:
wsj_sentiment=wsj.get_sentiments_from_wsj()

In [8]:
wsj_sentiment.index

Index(['1/1/00', '1/1/01', '1/1/02', '1/1/03', '1/1/04', '1/1/06', '1/1/07',
       '1/1/08', '1/1/09', '1/1/10',
       ...
       '9/9/11', '9/9/12', '9/9/13', '9/9/15', '9/9/16', '9/9/17', '9/9/18',
       '9/9/19', '9/9/20', '9/9/98'],
      dtype='object', name='Date', length=7977)

In [9]:
#sentiment_df = pd.merge(bear_sentiment['Bear_sum'], bull_sentiment['Bull_sum'], how='inner', left_on='Date', right_on='Date')
#sentiment_df = pd.merge(bear_sentiment, bull_sentiment, how='inner', left_on='Date', right_on='Date')

In [10]:
sentiment_df=sentiment_df.reset_index()

In [11]:
sentiment_df['Date']=pd.to_datetime(sentiment_df['Date'])

In [12]:
#df_cd = pd.merge(df_SN7577i_c, df_SN7577i_d, how='inner', left_on = 'Id', right_on = 'Id')
#sentiment_df = pd.merge(sentiment_df[['Bear_sum','Bull_sum']], wsj_sentiment['sentiment'], how='inner', left_on='Date', right_on='Date')

In [13]:
sentiment_df.set_index('Date')

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited
Date,,,,,,,,,,,,,,,
2018-04-01,15.0,126.0,39.0,164.0,24.0,8.0,35.0,22.0,2.0,6.0,1.0,188.0,87.0,40.0,100.0
2018-04-02,16.0,116.0,33.0,162.0,12.0,2.0,21.0,10.0,1.0,3.0,1.0,263.0,135.0,15.0,97.0
2018-04-03,26.0,155.0,45.0,171.0,29.0,8.0,30.0,15.0,2.0,1.0,2.0,306.0,121.0,26.0,111.0
2018-04-04,15.0,156.0,37.0,175.0,25.0,4.0,33.0,22.0,1.0,1.0,1.0,265.0,117.0,23.0,97.0
2018-04-05,20.0,123.0,44.0,179.0,29.0,7.0,25.0,20.0,4.0,4.0,1.0,252.0,117.0,22.0,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-21,30.0,110.0,24.0,75.0,16.0,2.0,17.0,14.0,4.0,1.0,3.0,147.0,80.0,12.0,75.0
2020-12-22,16.0,78.0,22.0,57.0,13.0,1.0,17.0,20.0,2.0,2.0,2.0,158.0,89.0,25.0,68.0
2020-12-23,18.0,83.0,35.0,64.0,10.0,3.0,22.0,8.0,2.0,3.0,1.0,134.0,72.0,24.0,78.0
2020-12-24,14.0,62.0,23.0,38.0,11.0,4.0,15.0,18.0,2.0,2.0,2.0,99.0,76.0,31.0,54.0
2020-12-25,7.0,59.0,19.0,25.0,12.0,0.0,5.0,8.0,4.0,0.0,0.0,108.0,54.0,31.0,58.0

In [14]:
wsj_sentiment=wsj_sentiment.reset_index()

In [15]:
wsj_sentiment['Date']=pd.to_datetime(wsj_sentiment['Date'])

In [16]:
wsj_sentiment=wsj_sentiment.set_index('Date')

In [17]:
wsj_sentiment=wsj_sentiment.groupby(by='Date').mean()

In [18]:
wsj_sentiment

              scores
Date
1998-01-07 -0.273200
1998-02-12  0.000000
1998-03-26  0.000000
1998-05-03  0.000000
1998-05-04  0.000000
...              ...
2021-06-26  0.152933
2021-06-27  0.000000
2021-06-28 -0.273200
2021-06-29  0.058233
2021-06-30 -0.159175

[7977 rows x 1 columns]

In [19]:
sentiment_df = pd.merge(sentiment_df, wsj_sentiment, how='inner', left_on='Date', right_on='Date')

In [20]:
sentiment_df = sentiment_df.set_index('Date')

In [21]:
df_coin= ld.load_from_yahoo([coin_ticker], start,end)

In [22]:
'''short_window=10
long_window = 100
df_coins=pd.DataFrame(df_coin[coin_ticker]['close'])
df_coins['sig']=0.0
df_coins['SMA_short'] = df_coins['close'].rolling(window=short_window).mean()
df_coins['SMA_long'] = df_coins['close'].rolling(window=long_window).mean()
df_coins['sig'][short_window:] = np.where(
    df_coins['SMA_short'][short_window:] > df_coins['SMA_long'][short_window:], 1.0, 0.0
    )
df_coins['signal'] = df_coins['sig'].diff()
    
df_coins[df_coins['signal']==-1]
'''

"short_window=10\nlong_window = 100\ndf_coins=pd.DataFrame(df_coin[coin_ticker]['close'])\ndf_coins['sig']=0.0\ndf_coins['SMA_short'] = df_coins['close'].rolling(window=short_window).mean()\ndf_coins['SMA_long'] = df_coins['close'].rolling(window=long_window).mean()\ndf_coins['sig'][short_window:] = np.where(\n    df_coins['SMA_short'][short_window:] > df_coins['SMA_long'][short_window:], 1.0, 0.0\n    )\ndf_coins['signal'] = df_coins['sig'].diff()\n    \ndf_coins[df_coins['signal']==-1]\n"

In [23]:
df_coin.index

DatetimeIndex(['2018-03-31', '2018-04-01', '2018-04-02', '2018-04-03',
               '2018-04-04', '2018-04-05', '2018-04-06', '2018-04-07',
               '2018-04-08', '2018-04-09',
               ...
               '2022-04-21', '2022-04-22', '2022-04-23', '2022-04-24',
               '2022-04-25', '2022-04-26', '2022-04-27', '2022-04-28',
               '2022-04-29', '2022-04-30'],
              dtype='datetime64[ns]', name='Date', length=1492, freq=None)

In [24]:
joined_df = sentiment_df.join(df_coin[coin_ticker]['close'])

In [25]:
joined_df['daily_ret']=joined_df['close'].pct_change().shift()

In [26]:
joined_df

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited,scores,close,daily_ret
Date,,,,,,,,,,,,,,,,,,
2018-04-01,15.0,126.0,39.0,164.0,24.0,8.0,35.0,22.0,2.0,6.0,1.0,188.0,87.0,40.0,100.0,0.170000,6844.229980,NaN
2018-04-02,16.0,116.0,33.0,162.0,12.0,2.0,21.0,10.0,1.0,3.0,1.0,263.0,135.0,15.0,97.0,-0.045900,7083.799805,NaN
2018-04-03,26.0,155.0,45.0,171.0,29.0,8.0,30.0,15.0,2.0,1.0,2.0,306.0,121.0,26.0,111.0,-0.458800,7456.109863,0.035003
2018-04-04,15.0,156.0,37.0,175.0,25.0,4.0,33.0,22.0,1.0,1.0,1.0,265.0,117.0,23.0,97.0,0.000000,6853.839844,0.052558
2018-04-05,20.0,123.0,44.0,179.0,29.0,7.0,25.0,20.0,4.0,4.0,1.0,252.0,117.0,22.0,98.0,-0.309633,6811.470215,-0.080775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-20,27.0,105.0,29.0,37.0,19.0,4.0,15.0,21.0,3.0,2.0,1.0,186.0,90.0,27.0,62.0,0.231567,23477.294922,0.031631
2020-12-21,30.0,110.0,24.0,75.0,16.0,2.0,17.0,14.0,4.0,1.0,3.0,147.0,80.0,12.0,75.0,-0.063800,22803.082031,-0.016445
2020-12-22,16.0,78.0,22.0,57.0,13.0,1.0,17.0,20.0,2.0,2.0,2.0,158.0,89.0,25.0,68.0,0.000000,23783.029297,-0.028718
2020-12-23,18.0,83.0,35.0,64.0,10.0,3.0,22.0,8.0,2.0,3.0,1.0,134.0,72.0,24.0,78.0,0.401900,23241.345703,0.042974
2020-12-24,14.0,62.0,23.0,38.0,11.0,4.0,15.0,18.0,2.0,2.0,2.0,99.0,76.0,31.0,54.0,0.238350,23735.949219,-0.022776

In [27]:
'''#polarity=[]
#subj=[]
signal=[]
cnt=True
#for i in f_df['Headline']:
for i in joined_df.index:
    #Bear_sum	Bull_sum	scores	
    if cnt : 
        i_previous = i
        signal.append(0)
        cnt = False
        continue
    if (joined_df['daily_ret'][i] >0 and joined_df['daily_ret'][i_previous] > 0) :
        signal.append(1)
    elif (joined_df['daily_ret'][i] < 0 and joined_df['daily_ret'][i_previous] < 0):
        signal.append(-1)
    else:
        signal.append(0)
    
    i_previous = i

'''

"#polarity=[]\n#subj=[]\nsignal=[]\ncnt=True\n#for i in f_df['Headline']:\nfor i in joined_df.index:\n    #Bear_sum\tBull_sum\tscores\t\n    if cnt : \n        i_previous = i\n        signal.append(0)\n        cnt = False\n        continue\n    if (joined_df['daily_ret'][i] >0 and joined_df['daily_ret'][i_previous] > 0) :\n        signal.append(1)\n    elif (joined_df['daily_ret'][i] < 0 and joined_df['daily_ret'][i_previous] < 0):\n        signal.append(-1)\n    else:\n        signal.append(0)\n    \n    i_previous = i\n\n"

In [28]:
only_price_change_signal=True

In [29]:
#USE DIFF FUNCTION TO DECIDE SIGNAL
if only_price_change_signal:
    joined_df['Diff'] = joined_df['daily_ret'].diff()
    joined_df['signal'] = joined_df['Diff'].apply(lambda x: 1 if x > 0.07 else -1 if x < 0.03 else 0)
    joined_df.drop(columns=['Diff'], inplace=True)
else:
    signal=[]
    #for i in f_df['Headline']:
    for i in joined_df.index:
        if (joined_df['scores'][i] > .5) and joined_df['daily_ret'][i] >0:
            signal.append(1)
        elif (joined_df['scores'][i]>0.0 and joined_df['scores'][i] <= .5) and joined_df['daily_ret'][i] < 0:
            signal.append(-1)
        else:
            signal.append(0)
    joined_df['signal']= signal

In [30]:
joined_df['signal']

Date
2018-04-01    0
2018-04-02    0
2018-04-03    0
2018-04-04   -1
2018-04-05   -1
             ..
2020-12-20   -1
2020-12-21   -1
2020-12-22   -1
2020-12-23    1
2020-12-24   -1
Name: signal, Length: 963, dtype: int64

In [31]:
joined_df

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited,scores,close,daily_ret,signal
Date,,,,,,,,,,,,,,,,,,,
2018-04-01,15.0,126.0,39.0,164.0,24.0,8.0,35.0,22.0,2.0,6.0,1.0,188.0,87.0,40.0,100.0,0.170000,6844.229980,NaN,0
2018-04-02,16.0,116.0,33.0,162.0,12.0,2.0,21.0,10.0,1.0,3.0,1.0,263.0,135.0,15.0,97.0,-0.045900,7083.799805,NaN,0
2018-04-03,26.0,155.0,45.0,171.0,29.0,8.0,30.0,15.0,2.0,1.0,2.0,306.0,121.0,26.0,111.0,-0.458800,7456.109863,0.035003,0
2018-04-04,15.0,156.0,37.0,175.0,25.0,4.0,33.0,22.0,1.0,1.0,1.0,265.0,117.0,23.0,97.0,0.000000,6853.839844,0.052558,-1
2018-04-05,20.0,123.0,44.0,179.0,29.0,7.0,25.0,20.0,4.0,4.0,1.0,252.0,117.0,22.0,98.0,-0.309633,6811.470215,-0.080775,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-20,27.0,105.0,29.0,37.0,19.0,4.0,15.0,21.0,3.0,2.0,1.0,186.0,90.0,27.0,62.0,0.231567,23477.294922,0.031631,-1
2020-12-21,30.0,110.0,24.0,75.0,16.0,2.0,17.0,14.0,4.0,1.0,3.0,147.0,80.0,12.0,75.0,-0.063800,22803.082031,-0.016445,-1
2020-12-22,16.0,78.0,22.0,57.0,13.0,1.0,17.0,20.0,2.0,2.0,2.0,158.0,89.0,25.0,68.0,0.000000,23783.029297,-0.028718,-1
2020-12-23,18.0,83.0,35.0,64.0,10.0,3.0,22.0,8.0,2.0,3.0,1.0,134.0,72.0,24.0,78.0,0.401900,23241.345703,0.042974,1
2020-12-24,14.0,62.0,23.0,38.0,11.0,4.0,15.0,18.0,2.0,2.0,2.0,99.0,76.0,31.0,54.0,0.238350,23735.949219,-0.022776,-1

In [32]:
joined_df=joined_df.dropna()

In [33]:
joined_df

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited,scores,close,daily_ret,signal
Date,,,,,,,,,,,,,,,,,,,
2018-04-03,26.0,155.0,45.0,171.0,29.0,8.0,30.0,15.0,2.0,1.0,2.0,306.0,121.0,26.0,111.0,-0.458800,7456.109863,0.035003,0
2018-04-04,15.0,156.0,37.0,175.0,25.0,4.0,33.0,22.0,1.0,1.0,1.0,265.0,117.0,23.0,97.0,0.000000,6853.839844,0.052558,-1
2018-04-05,20.0,123.0,44.0,179.0,29.0,7.0,25.0,20.0,4.0,4.0,1.0,252.0,117.0,22.0,98.0,-0.309633,6811.470215,-0.080775,-1
2018-04-06,18.0,142.0,28.0,175.0,23.0,9.0,29.0,10.0,3.0,0.0,3.0,219.0,103.0,18.0,108.0,-0.007550,6636.319824,-0.006182,1
2018-04-07,22.0,122.0,42.0,120.0,10.0,3.0,21.0,13.0,3.0,2.0,1.0,208.0,111.0,14.0,97.0,-0.401000,6911.089844,-0.025714,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-20,27.0,105.0,29.0,37.0,19.0,4.0,15.0,21.0,3.0,2.0,1.0,186.0,90.0,27.0,62.0,0.231567,23477.294922,0.031631,-1
2020-12-21,30.0,110.0,24.0,75.0,16.0,2.0,17.0,14.0,4.0,1.0,3.0,147.0,80.0,12.0,75.0,-0.063800,22803.082031,-0.016445,-1
2020-12-22,16.0,78.0,22.0,57.0,13.0,1.0,17.0,20.0,2.0,2.0,2.0,158.0,89.0,25.0,68.0,0.000000,23783.029297,-0.028718,-1
2020-12-23,18.0,83.0,35.0,64.0,10.0,3.0,22.0,8.0,2.0,3.0,1.0,134.0,72.0,24.0,78.0,0.401900,23241.345703,0.042974,1
2020-12-24,14.0,62.0,23.0,38.0,11.0,4.0,15.0,18.0,2.0,2.0,2.0,99.0,76.0,31.0,54.0,0.238350,23735.949219,-0.022776,-1

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [35]:
y = joined_df['signal']
if only_price_change_signal:
    X = joined_df.drop(columns=['daily_ret', 'close', 'signal'])
else:
    X = joined_df.drop(columns=['scores', 'daily_ret', 'close', 'signal'])

In [36]:
X.to_csv('X.csv')
y.to_csv('y.csv')

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited,scores
Date,,,,,,,,,,,,,,,,
2019-08-16,12.0,90.0,22.0,99.0,18.0,11.0,38.0,9.0,2.0,1.0,2.0,129.0,106.0,13.0,89.0,-0.249967
2020-05-13,14.0,86.0,37.0,64.0,17.0,2.0,14.0,14.0,4.0,1.0,1.0,169.0,68.0,16.0,73.0,-0.016950
2018-10-22,15.0,121.0,28.0,88.0,18.0,3.0,13.0,5.0,6.0,0.0,3.0,194.0,105.0,12.0,78.0,-0.289300
2018-11-24,19.0,156.0,40.0,139.0,32.0,5.0,17.0,24.0,3.0,10.0,4.0,202.0,84.0,24.0,97.0,-0.137850
2019-06-26,82.0,275.0,50.0,133.0,30.0,9.0,0.0,42.0,13.0,7.0,2.0,429.0,124.0,47.0,240.0,-0.269925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-11-11,6.0,64.0,17.0,41.0,23.0,3.0,19.0,6.0,3.0,3.0,0.0,63.0,69.0,11.0,39.0,0.258800
2020-05-16,9.0,98.0,27.0,46.0,27.0,4.0,16.0,17.0,1.0,0.0,2.0,127.0,77.0,23.0,65.0,-0.074667
2018-09-03,19.0,145.0,29.0,102.0,19.0,0.0,15.0,6.0,1.0,0.0,1.0,305.0,125.0,16.0,89.0,-0.296000
2018-06-08,12.0,111.0,27.0,80.0,19.0,8.0,23.0,9.0,9.0,3.0,1.0,200.0,125.0,17.0,81.0,0.164633
2018-04-08,16.0,122.0,41.0,90.0,34.0,4.0,19.0,24.0,1.0,3.0,1.0,213.0,98.0,24.0,95.0,-0.296000

In [38]:
# Scale the data
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [39]:
X_train_scaled.shape

(720, 16)

In [40]:
# Import ClusterCentroids from imblearn
from imblearn.under_sampling import ClusterCentroids

# Instantiate a ClusterCentroids instance
cc_sampler = ClusterCentroids(random_state=1)
# Fit the training data to the cluster centroids model
X_resampled, y_resampled = cc_sampler.fit_resample(X_train_scaled, y_train)

In [41]:
# Count distinct values for the resampled target data
y_resampled.value_counts()

-1    45
 0    45
 1    45
Name: signal, dtype: int64

In [42]:
lr = LogisticRegression()

In [43]:
lr.fit(X_resampled, y_resampled)
# Make predictions using the test data
y_pred = lr.predict(X_test_scaled)

results = pd.DataFrame({
    "Prediction": y_pred, 
    "Actual": y_test
}).reset_index(drop=True)

results.head()

   Prediction  Actual
0           1      -1
1           1      -1
2           1      -1
3           0      -1
4           1      -1

In [44]:
# Make predictions using the test data
y_pred = lr.predict(X_test_scaled)

results = pd.DataFrame({
    "Prediction": y_pred, 
    "Actual": y_test
}).reset_index(drop=True)

results.head()

   Prediction  Actual
0           1      -1
1           1      -1
2           1      -1
3           0      -1
4           1      -1

In [45]:
# Import Modules
from sklearn.metrics import confusion_matrix,classification_report

In [46]:
# Print confusion matrix
print(confusion_matrix(y_test, y_pred))

[[48 48 93]
 [ 3 16 12]
 [ 5  4 12]]

In [47]:
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       0.86      0.25      0.39       189
           0       0.24      0.52      0.32        31
           1       0.10      0.57      0.17        21

    accuracy                           0.32       241
   macro avg       0.40      0.45      0.30       241
weighted avg       0.71      0.32      0.36       241

In [48]:
#get the current news and data from augmento
#run the data prep to get the X_test_scaled data so it can be tested

In [49]:
# Instantiate a linear SVM model
from sklearn.svm import SVC
svm = SVC(kernel='linear')
# Fit the data
svm.fit(X_resampled, y_resampled)
# Make predictions using the test data
y_pred = svm.predict(X_test_scaled)

results = pd.DataFrame({
    "Prediction": y_pred, 
    "Actual": y_test
}).reset_index(drop=True)

results.head()
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       0.91      0.28      0.43       189
           0       0.27      0.39      0.32        31
           1       0.11      0.71      0.19        21

    accuracy                           0.33       241
   macro avg       0.43      0.46      0.31       241
weighted avg       0.76      0.33      0.39       241

In [50]:
'''
c_rep=[]
c_rep.append(classification_report(y_test, y_pred, output_dict=True))
c_rep[0]['Name']="twitter"
c_rep[0]
'''

'\nc_rep=[]\nc_rep.append(classification_report(y_test, y_pred, output_dict=True))\nc_rep[0][\'Name\']="twitter"\nc_rep[0]\n'

In [51]:
#c_df.transpose