In [1]:
import pandas as pd
import requests
from pathlib import Path
import json
import datetime

import numpy as np

import load_data as ld
import os

import twitter_lib as tl
import wsj_lib as wsj

In [2]:
coin = 'bitcoin'
coin_ticker='BTC-USD'
num_of_periods = 1000 # 1000 days

start="2019-04-01T00:00:00Z"
end ="2022-01-30T00:00:00Z"
#default bin size of 24H, but we will provide ...just..
bin_size='24H'

In [3]:
sentiment_df = tl.get_crypto_sentiment_from_twitter(coin, num_of_periods, start, end, bin_size)

In [4]:
#bear_sentiment, bull_sentiment = tl.get_crypto_sentiment_from_twitter(coin, num_of_periods, start, end, bin_size)

In [5]:
#bear_sentiment

In [6]:
#bull_sentiment

In [7]:
sentiment_df.head()

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited
Date,,,,,,,,,,,,,,,
2019-04-01,14.0,81.0,23.0,123.0,14.0,3.0,17.0,9.0,4.0,0.0,1.0,233.0,82.0,11.0,76.0
2019-04-02,58.0,216.0,78.0,199.0,42.0,7.0,35.0,32.0,1.0,10.0,2.0,523.0,129.0,58.0,223.0
2019-04-03,49.0,198.0,42.0,163.0,28.0,11.0,22.0,21.0,5.0,3.0,9.0,433.0,103.0,22.0,164.0
2019-04-04,20.0,115.0,35.0,145.0,19.0,4.0,22.0,9.0,4.0,2.0,2.0,262.0,90.0,19.0,81.0
2019-04-05,17.0,112.0,24.0,90.0,17.0,1.0,29.0,6.0,4.0,2.0,1.0,245.0,103.0,18.0,65.0

In [8]:
#sentiment_df = pd.merge(bear_sentiment['Bear_sum'], bull_sentiment['Bull_sum'], how='inner', left_on='Date', right_on='Date')
#sentiment_df = pd.merge(bear_sentiment, bull_sentiment, how='inner', left_on='Date', right_on='Date')

In [9]:
sentiment_df=sentiment_df.reset_index()

In [10]:
sentiment_df['Date']=pd.to_datetime(sentiment_df['Date'])

In [11]:
#df_cd = pd.merge(df_SN7577i_c, df_SN7577i_d, how='inner', left_on = 'Id', right_on = 'Id')
#sentiment_df = pd.merge(sentiment_df[['Bear_sum','Bull_sum']], wsj_sentiment['sentiment'], how='inner', left_on='Date', right_on='Date')

In [12]:
sentiment_df.set_index('Date')

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited
Date,,,,,,,,,,,,,,,
2019-04-01,14.0,81.0,23.0,123.0,14.0,3.0,17.0,9.0,4.0,0.0,1.0,233.0,82.0,11.0,76.0
2019-04-02,58.0,216.0,78.0,199.0,42.0,7.0,35.0,32.0,1.0,10.0,2.0,523.0,129.0,58.0,223.0
2019-04-03,49.0,198.0,42.0,163.0,28.0,11.0,22.0,21.0,5.0,3.0,9.0,433.0,103.0,22.0,164.0
2019-04-04,20.0,115.0,35.0,145.0,19.0,4.0,22.0,9.0,4.0,2.0,2.0,262.0,90.0,19.0,81.0
2019-04-05,17.0,112.0,24.0,90.0,17.0,1.0,29.0,6.0,4.0,2.0,1.0,245.0,103.0,18.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-21,7.0,59.0,18.0,44.0,14.0,3.0,7.0,5.0,1.0,0.0,2.0,128.0,72.0,14.0,37.0
2021-12-22,10.0,31.0,16.0,32.0,8.0,1.0,6.0,2.0,2.0,2.0,2.0,99.0,48.0,16.0,35.0
2021-12-23,9.0,53.0,17.0,30.0,8.0,3.0,8.0,3.0,2.0,1.0,2.0,106.0,55.0,11.0,46.0
2021-12-24,6.0,39.0,18.0,13.0,7.0,3.0,8.0,1.0,1.0,0.0,1.0,81.0,26.0,27.0,20.0
2021-12-25,6.0,23.0,9.0,21.0,5.0,2.0,7.0,1.0,2.0,0.0,0.0,44.0,24.0,14.0,22.0

In [13]:
df_coin= ld.load_from_yahoo([coin_ticker], start,end)

In [14]:
'''short_window=10
long_window = 100
df_coins=pd.DataFrame(df_coin[coin_ticker]['close'])
df_coins['sig']=0.0
df_coins['SMA_short'] = df_coins['close'].rolling(window=short_window).mean()
df_coins['SMA_long'] = df_coins['close'].rolling(window=long_window).mean()
df_coins['sig'][short_window:] = np.where(
    df_coins['SMA_short'][short_window:] > df_coins['SMA_long'][short_window:], 1.0, 0.0
    )
df_coins['signal'] = df_coins['sig'].diff()
    
df_coins[df_coins['signal']==-1]
'''

"short_window=10\nlong_window = 100\ndf_coins=pd.DataFrame(df_coin[coin_ticker]['close'])\ndf_coins['sig']=0.0\ndf_coins['SMA_short'] = df_coins['close'].rolling(window=short_window).mean()\ndf_coins['SMA_long'] = df_coins['close'].rolling(window=long_window).mean()\ndf_coins['sig'][short_window:] = np.where(\n    df_coins['SMA_short'][short_window:] > df_coins['SMA_long'][short_window:], 1.0, 0.0\n    )\ndf_coins['signal'] = df_coins['sig'].diff()\n    \ndf_coins[df_coins['signal']==-1]\n"

In [15]:
df_coin

                 BTC-USD                                            \
                    high           low          open         close
Date
2019-03-31   4113.023438   4094.100830   4105.456055   4105.404297
2019-04-01   4164.953125   4096.901367   4105.362305   4158.183105
2019-04-02   4905.954590   4155.316895   4156.919434   4879.877930
2019-04-03   5307.003418   4876.621094   4879.958008   4973.021973
2019-04-04   5063.159668   4836.793945   4971.307617   4922.798828
...                  ...           ...           ...           ...
2022-01-26  38825.410156  36374.906250  36950.515625  36852.121094
2022-01-27  37148.324219  35629.281250  36841.878906  37138.234375
2022-01-28  37952.878906  36211.109375  37128.445312  37784.332031
2022-01-29  38576.261719  37406.472656  37780.714844  38138.179688
2022-01-30  38266.339844  37437.710938  38151.917969  37917.601562


                 volume     adj close
Date
2019-03-31   9045122443   4105.404297
2019-04-01  10157794171   4158.183105
2019-04-02  21315047816   4879.877930
2019-04-03  22899891582   4973.021973
2019-04-04  18251810240   4922.798828
...                 ...           ...
2022-01-26  31324598034  36852.121094
2022-01-27  25041426629  37138.234375
2022-01-28  22238830523  37784.332031
2022-01-29  17194183075  38138.179688
2022-01-30  14643548444  37917.601562

[1037 rows x 6 columns]

In [16]:
df_coin.index

DatetimeIndex(['2019-03-31', '2019-04-01', '2019-04-02', '2019-04-03',
               '2019-04-04', '2019-04-05', '2019-04-06', '2019-04-07',
               '2019-04-08', '2019-04-09',
               ...
               '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
               '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
               '2022-01-29', '2022-01-30'],
              dtype='datetime64[ns]', name='Date', length=1037, freq=None)

In [17]:
#joined_df = sentiment_df.join(df_coin[coin_ticker]['close'])

In [19]:
#sentiment_df = pd.merge(sentiment_df[['Bear_sum','Bull_sum']], wsj_sentiment['sentiment'], how='inner', left_on='Date', right_on='Date')
joined_df = pd.merge(sentiment_df, df_coin[coin_ticker]['adj close'], how='inner', left_on='Date', right_on='Date')

In [20]:
joined_df

,Date,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited,adj close
0,2019-04-01,14.0,81.0,23.0,123.0,14.0,3.0,17.0,9.0,4.0,0.0,1.0,233.0,82.0,11.0,76.0,4158.183105
1,2019-04-02,58.0,216.0,78.0,199.0,42.0,7.0,35.0,32.0,1.0,10.0,2.0,523.0,129.0,58.0,223.0,4879.877930
2,2019-04-03,49.0,198.0,42.0,163.0,28.0,11.0,22.0,21.0,5.0,3.0,9.0,433.0,103.0,22.0,164.0,4973.021973
3,2019-04-04,20.0,115.0,35.0,145.0,19.0,4.0,22.0,9.0,4.0,2.0,2.0,262.0,90.0,19.0,81.0,4922.798828
4,2019-04-05,17.0,112.0,24.0,90.0,17.0,1.0,29.0,6.0,4.0,2.0,1.0,245.0,103.0,18.0,65.0,5036.681152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2021-12-21,7.0,59.0,18.0,44.0,14.0,3.0,7.0,5.0,1.0,0.0,2.0,128.0,72.0,14.0,37.0,48936.613281
996,2021-12-22,10.0,31.0,16.0,32.0,8.0,1.0,6.0,2.0,2.0,2.0,2.0,99.0,48.0,16.0,35.0,48628.511719
997,2021-12-23,9.0,53.0,17.0,30.0,8.0,3.0,8.0,3.0,2.0,1.0,2.0,106.0,55.0,11.0,46.0,50784.539062
998,2021-12-24,6.0,39.0,18.0,13.0,7.0,3.0,8.0,1.0,1.0,0.0,1.0,81.0,26.0,27.0,20.0,50822.195312
999,2021-12-25,6.0,23.0,9.0,21.0,5.0,2.0,7.0,1.0,2.0,0.0,0.0,44.0,24.0,14.0,22.0,50429.859375

In [21]:
joined_df['daily_ret']=joined_df['adj close'].pct_change().shift()

In [ ]:
#joined_df['bear']=sentiment_df[[ 'Bearish', 'Pessimistic/Doubtful', 'Sad', 'Fearful/Concerned', 'Angry', 'Mistrustful', 'Panicking', 'Annoyed/Frustrated']].sum(axis=1)/1000
#joined_df['bear']

In [ ]:
#joined_df['bull'] = sentiment_df[[ 'Hopeful','Bullish', 'Optimistic', 'Happy', 'Euphoric/Excited']].sum(axis=1)/1000
#joined_df['bull']

In [ ]:
#joined_df['net']= joined_df['Bullish'] - joined_df['Bearish']

In [ ]:
#joined_df[joined_df['net'] < 0]

In [ ]:
#short_window = 5
#long_window = 50

In [ ]:
#joined_df['SENTIMENT_short_wsj']=joined_df['scores'].rolling(window=short_window).mean()
#joined_df['SENTIMENT_long_wsj']=joined_df['scores'].rolling(window=long_window).mean()

In [ ]:
#X=joined_df[['SENTIMENT_short_wsj', 'SENTIMENT_long_wsj']].copy()

In [35]:
joined_df['signal'] = 0.0
joined_df.loc[(joined_df['daily_ret'] >= 0), 'signal'] = 1
joined_df.loc[(joined_df['daily_ret'] < 0), 'signal'] = -1

/Users/ashokpandey/opt/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/ashokpandey/opt/anaconda3/envs/dev/lib/python3.7/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [36]:
joined_df

,Date,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited,adj close,daily_ret,signal
2,2019-04-03,49.0,198.0,42.0,163.0,28.0,11.0,22.0,21.0,5.0,3.0,9.0,433.0,103.0,22.0,164.0,4973.021973,0.173560,1.0
3,2019-04-04,20.0,115.0,35.0,145.0,19.0,4.0,22.0,9.0,4.0,2.0,2.0,262.0,90.0,19.0,81.0,4922.798828,0.019087,1.0
4,2019-04-05,17.0,112.0,24.0,90.0,17.0,1.0,29.0,6.0,4.0,2.0,1.0,245.0,103.0,18.0,65.0,5036.681152,-0.010099,-1.0
5,2019-04-06,12.0,86.0,24.0,84.0,25.0,3.0,14.0,6.0,3.0,2.0,1.0,243.0,60.0,11.0,63.0,5059.817383,0.023134,1.0
6,2019-04-07,15.0,96.0,17.0,96.0,12.0,1.0,8.0,12.0,1.0,1.0,4.0,220.0,66.0,14.0,64.0,5198.896973,0.004594,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2021-12-21,7.0,59.0,18.0,44.0,14.0,3.0,7.0,5.0,1.0,0.0,2.0,128.0,72.0,14.0,37.0,48936.613281,0.003710,1.0
996,2021-12-22,10.0,31.0,16.0,32.0,8.0,1.0,6.0,2.0,2.0,2.0,2.0,99.0,48.0,16.0,35.0,48628.511719,0.043864,1.0
997,2021-12-23,9.0,53.0,17.0,30.0,8.0,3.0,8.0,3.0,2.0,1.0,2.0,106.0,55.0,11.0,46.0,50784.539062,-0.006296,-1.0
998,2021-12-24,6.0,39.0,18.0,13.0,7.0,3.0,8.0,1.0,1.0,0.0,1.0,81.0,26.0,27.0,20.0,50822.195312,0.044337,1.0
999,2021-12-25,6.0,23.0,9.0,21.0,5.0,2.0,7.0,1.0,2.0,0.0,0.0,44.0,24.0,14.0,22.0,50429.859375,0.000741,1.0

In [37]:
joined_df=joined_df.dropna()

In [38]:
joined_df.set_index('Date')

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited,adj close,daily_ret,signal
Date,,,,,,,,,,,,,,,,,,
2019-04-03,49.0,198.0,42.0,163.0,28.0,11.0,22.0,21.0,5.0,3.0,9.0,433.0,103.0,22.0,164.0,4973.021973,0.173560,1.0
2019-04-04,20.0,115.0,35.0,145.0,19.0,4.0,22.0,9.0,4.0,2.0,2.0,262.0,90.0,19.0,81.0,4922.798828,0.019087,1.0
2019-04-05,17.0,112.0,24.0,90.0,17.0,1.0,29.0,6.0,4.0,2.0,1.0,245.0,103.0,18.0,65.0,5036.681152,-0.010099,-1.0
2019-04-06,12.0,86.0,24.0,84.0,25.0,3.0,14.0,6.0,3.0,2.0,1.0,243.0,60.0,11.0,63.0,5059.817383,0.023134,1.0
2019-04-07,15.0,96.0,17.0,96.0,12.0,1.0,8.0,12.0,1.0,1.0,4.0,220.0,66.0,14.0,64.0,5198.896973,0.004594,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-21,7.0,59.0,18.0,44.0,14.0,3.0,7.0,5.0,1.0,0.0,2.0,128.0,72.0,14.0,37.0,48936.613281,0.003710,1.0
2021-12-22,10.0,31.0,16.0,32.0,8.0,1.0,6.0,2.0,2.0,2.0,2.0,99.0,48.0,16.0,35.0,48628.511719,0.043864,1.0
2021-12-23,9.0,53.0,17.0,30.0,8.0,3.0,8.0,3.0,2.0,1.0,2.0,106.0,55.0,11.0,46.0,50784.539062,-0.006296,-1.0
2021-12-24,6.0,39.0,18.0,13.0,7.0,3.0,8.0,1.0,1.0,0.0,1.0,81.0,26.0,27.0,20.0,50822.195312,0.044337,1.0
2021-12-25,6.0,23.0,9.0,21.0,5.0,2.0,7.0,1.0,2.0,0.0,0.0,44.0,24.0,14.0,22.0,50429.859375,0.000741,1.0

In [31]:
#joined_df['diff_signal'] = joined_df['signal'].diff()

In [32]:
#X=joined_df[['SENTIMENT_short_wsj', 'SENTIMENT_long_wsj']].copy()
#y = joined_df['diff_signal'].copy()

In [49]:
joined_df=joined_df.set_index('Date')

In [50]:
y=joined_df['signal']

In [51]:
X=joined_df.drop(columns=['signal', 'daily_ret', 'adj close'])

In [52]:
X

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited
Date,,,,,,,,,,,,,,,
2019-04-03,49.0,198.0,42.0,163.0,28.0,11.0,22.0,21.0,5.0,3.0,9.0,433.0,103.0,22.0,164.0
2019-04-04,20.0,115.0,35.0,145.0,19.0,4.0,22.0,9.0,4.0,2.0,2.0,262.0,90.0,19.0,81.0
2019-04-05,17.0,112.0,24.0,90.0,17.0,1.0,29.0,6.0,4.0,2.0,1.0,245.0,103.0,18.0,65.0
2019-04-06,12.0,86.0,24.0,84.0,25.0,3.0,14.0,6.0,3.0,2.0,1.0,243.0,60.0,11.0,63.0
2019-04-07,15.0,96.0,17.0,96.0,12.0,1.0,8.0,12.0,1.0,1.0,4.0,220.0,66.0,14.0,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-21,7.0,59.0,18.0,44.0,14.0,3.0,7.0,5.0,1.0,0.0,2.0,128.0,72.0,14.0,37.0
2021-12-22,10.0,31.0,16.0,32.0,8.0,1.0,6.0,2.0,2.0,2.0,2.0,99.0,48.0,16.0,35.0
2021-12-23,9.0,53.0,17.0,30.0,8.0,3.0,8.0,3.0,2.0,1.0,2.0,106.0,55.0,11.0,46.0
2021-12-24,6.0,39.0,18.0,13.0,7.0,3.0,8.0,1.0,1.0,0.0,1.0,81.0,26.0,27.0,20.0
2021-12-25,6.0,23.0,9.0,21.0,5.0,2.0,7.0,1.0,2.0,0.0,0.0,44.0,24.0,14.0,22.0

In [53]:
#import hvplot.pandas

In [54]:
#joined_df[['bull', 'bear', 'daily_ret']].hvplot(figsize=(10,4))

In [55]:
'''#polarity=[]
#subj=[]
signal=[]
cnt=True
#for i in f_df['Headline']:
for i in joined_df.index:
    #Bear_sum	Bull_sum	scores	
    if cnt : 
        i_previous = i
        signal.append(0)
        cnt = False
        continue
    if (joined_df['daily_ret'][i] >0 and joined_df['daily_ret'][i_previous] > 0) :
        signal.append(1)
    elif (joined_df['daily_ret'][i] < 0 and joined_df['daily_ret'][i_previous] < 0):
        signal.append(-1)
    else:
        signal.append(0)
    
    i_previous = i

'''

"#polarity=[]\n#subj=[]\nsignal=[]\ncnt=True\n#for i in f_df['Headline']:\nfor i in joined_df.index:\n    #Bear_sum\tBull_sum\tscores\t\n    if cnt : \n        i_previous = i\n        signal.append(0)\n        cnt = False\n        continue\n    if (joined_df['daily_ret'][i] >0 and joined_df['daily_ret'][i_previous] > 0) :\n        signal.append(1)\n    elif (joined_df['daily_ret'][i] < 0 and joined_df['daily_ret'][i_previous] < 0):\n        signal.append(-1)\n    else:\n        signal.append(0)\n    \n    i_previous = i\n\n"

In [56]:
#only_price_change_signal=True

In [57]:
'''
#USE DIFF FUNCTION TO DECIDE SIGNAL
if only_price_change_signal:
    joined_df['Diff'] = joined_df['daily_ret'].diff()
    joined_df['signal'] = joined_df['Diff'].apply(lambda x: 1 if x > 0.07 else -1 if x < 0.03 else 0)
    joined_df.drop(columns=['Diff'], inplace=True)
else:
    signal=[]
    #for i in f_df['Headline']:
    for i in joined_df.index:
        if (joined_df['scores'][i] > .5) and joined_df['daily_ret'][i] >0:
            signal.append(1)
        elif (joined_df['scores'][i]>0.0 and joined_df['scores'][i] <= .5) and joined_df['daily_ret'][i] < 0:
            signal.append(-1)
        else:
            signal.append(0)
    joined_df['signal']= signal
'''

"\n#USE DIFF FUNCTION TO DECIDE SIGNAL\nif only_price_change_signal:\n    joined_df['Diff'] = joined_df['daily_ret'].diff()\n    joined_df['signal'] = joined_df['Diff'].apply(lambda x: 1 if x > 0.07 else -1 if x < 0.03 else 0)\n    joined_df.drop(columns=['Diff'], inplace=True)\nelse:\n    signal=[]\n    #for i in f_df['Headline']:\n    for i in joined_df.index:\n        if (joined_df['scores'][i] > .5) and joined_df['daily_ret'][i] >0:\n            signal.append(1)\n        elif (joined_df['scores'][i]>0.0 and joined_df['scores'][i] <= .5) and joined_df['daily_ret'][i] < 0:\n            signal.append(-1)\n        else:\n            signal.append(0)\n    joined_df['signal']= signal\n"

In [58]:
#joined_df[joined_df['signal']==1]

In [59]:
#joined_df[joined_df['signal']==-1]

In [60]:
#joined_df

In [61]:
#joined_df=joined_df.dropna()

In [62]:
#joined_df

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [64]:
'''
y = joined_df['signal']
if only_price_change_signal:
    X = joined_df.drop(columns=['daily_ret', 'close', 'signal'])
else:
    X = joined_df.drop(columns=['scores', 'daily_ret', 'close', 'signal'])
'''

"\ny = joined_df['signal']\nif only_price_change_signal:\n    X = joined_df.drop(columns=['daily_ret', 'close', 'signal'])\nelse:\n    X = joined_df.drop(columns=['scores', 'daily_ret', 'close', 'signal'])\n"

In [65]:
X.to_csv('X.csv')
y.to_csv('y.csv')

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train

,FOMO,Uncertain,Hopeful,Bearish,Pessimistic/Doubtful,Sad,Fearful/Concerned,Angry,Mistrustful,Panicking,Annoyed/Frustrated,Bullish,Optimistic,Happy,Euphoric/Excited
Date,,,,,,,,,,,,,,,
2021-07-05,3.0,76.0,15.0,46.0,4.0,1.0,16.0,3.0,1.0,0.0,3.0,116.0,25.0,12.0,21.0
2021-08-03,7.0,51.0,16.0,45.0,9.0,2.0,16.0,5.0,1.0,0.0,3.0,129.0,31.0,6.0,34.0
2019-04-05,17.0,112.0,24.0,90.0,17.0,1.0,29.0,6.0,4.0,2.0,1.0,245.0,103.0,18.0,65.0
2020-12-07,17.0,82.0,23.0,35.0,10.0,1.0,11.0,5.0,1.0,0.0,1.0,146.0,76.0,11.0,72.0
2021-08-25,11.0,47.0,12.0,41.0,9.0,5.0,11.0,10.0,1.0,1.0,1.0,115.0,48.0,8.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-06,12.0,62.0,23.0,68.0,11.0,3.0,26.0,9.0,2.0,2.0,1.0,112.0,57.0,13.0,48.0
2020-02-19,8.0,102.0,45.0,63.0,18.0,2.0,21.0,12.0,5.0,4.0,2.0,180.0,86.0,9.0,78.0
2021-04-22,9.0,97.0,40.0,105.0,21.0,5.0,34.0,13.0,2.0,6.0,1.0,194.0,86.0,21.0,75.0
2019-05-25,17.0,119.0,27.0,65.0,15.0,7.0,27.0,13.0,3.0,1.0,1.0,197.0,79.0,20.0,54.0
2019-08-02,17.0,95.0,25.0,99.0,28.0,3.0,13.0,7.0,2.0,3.0,1.0,185.0,118.0,28.0,69.0

In [69]:
# Scale the data
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [70]:
X_train_scaled.shape

(748, 15)

In [71]:
# Import ClusterCentroids from imblearn
from imblearn.under_sampling import ClusterCentroids

# Instantiate a ClusterCentroids instance
cc_sampler = ClusterCentroids(random_state=1)
# Fit the training data to the cluster centroids model
X_resampled, y_resampled = cc_sampler.fit_resample(X_train_scaled, y_train)

In [72]:
# Count distinct values for the resampled target data
y_resampled.value_counts()

-1.0    353
 1.0    353
Name: signal, dtype: int64

In [73]:
lr = LogisticRegression()

In [74]:
lr.fit(X_resampled, y_resampled)
# Make predictions using the test data
y_pred = lr.predict(X_test_scaled)

results = pd.DataFrame({
    "Prediction": y_pred, 
    "Actual": y_test
}).reset_index(drop=True)

results.head()

   Prediction  Actual
0         1.0     1.0
1        -1.0     1.0
2         1.0     1.0
3        -1.0    -1.0
4        -1.0    -1.0

In [75]:
# Make predictions using the test data
y_pred = lr.predict(X_test_scaled)

results = pd.DataFrame({
    "Prediction": y_pred, 
    "Actual": y_test
}).reset_index(drop=True)

results.head()

   Prediction  Actual
0         1.0     1.0
1        -1.0     1.0
2         1.0     1.0
3        -1.0    -1.0
4        -1.0    -1.0

In [76]:
# Import Modules
from sklearn.metrics import confusion_matrix,classification_report

In [77]:
# Print confusion matrix
print(confusion_matrix(y_test, y_pred))

[[68 46]
 [51 85]]

In [78]:
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        -1.0       0.57      0.60      0.58       114
         1.0       0.65      0.62      0.64       136

    accuracy                           0.61       250
   macro avg       0.61      0.61      0.61       250
weighted avg       0.61      0.61      0.61       250

In [79]:
#get the current news and data from augmento
#run the data prep to get the X_test_scaled data so it can be tested

In [80]:
# Instantiate a linear SVM model
from sklearn.svm import SVC
svm = SVC(kernel='linear')
# Fit the data
svm.fit(X_resampled, y_resampled)
# Make predictions using the test data
y_pred = svm.predict(X_test_scaled)

results = pd.DataFrame({
    "Prediction": y_pred, 
    "Actual": y_test
}).reset_index(drop=True)

results.head()
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        -1.0       0.57      0.62      0.59       114
         1.0       0.66      0.60      0.63       136

    accuracy                           0.61       250
   macro avg       0.61      0.61      0.61       250
weighted avg       0.62      0.61      0.61       250

In [ ]:
'''
c_rep=[]
c_rep.append(classification_report(y_test, y_pred, output_dict=True))
c_rep[0]['Name']="twitter"
c_rep[0]
'''

In [ ]:
#c_df.transpose

In [ ]:
print('I m done..')

In [ ]:
import os
os.getcwd()

In [ ]:
X.to_csv('X_eth.csv')